### ISSUE TITLE
Version of IgH ethercat code

### ISSUE THREAD

**Issue by elias10101** [ethercat-rs/ethercat#16]
Nice work! Which version of the IgH Ethercat master code are you using for this wrapper?

**Comment by birkenfeld** [comment]
I was working with the `default` branch of the hg repository.  Now I checked again and saw that apparently the IgH people are working exclusively on the `stable-1.5` branch...

But I think it shouldn't matter too much; it looks the ioctl interface we use between userspace and kernelspace hasn't changed except for a shift in the ioctl numbers. You just need to generate the Rust bindings with the version you're also building the kernel module from.

**Comment by flosse** [comment]
Unfortunately there are differences... even between `v1.5.2-sncn-7` and `v1.5.2-sncn-11` (look at `master/ioctl.h`).
See #17  (PR to update to `v1.5.2-sncn-11`).

**Comment by birkenfeld** [comment]
Ah damn, we aren't pulling the ioctl numbers from the header file... should we?

**Comment by birkenfeld** [comment]
In fact, it should be quite straightforward to autogenerate the `ioctl!` definitions from the `#define`s in `ioctl.h`.

**Comment by birkenfeld** [comment]
In any case, we should definitely point to the "canonical" branch we test with in the README.

**Comment by flosse** [comment]
Done with #22

**Comment by flosse** [comment]
... and 9f24c1b6bd44c2c8ee2a3c942876351febfb80f2
