### ISSUE TITLE
Build with original IgH code?

### ISSUE THREAD

**Issue by birkenfeld** [ethercat-rs/ethercat#20]
It appears that f19eac75c47fe0c1dddc8180ada068dc70e1a4be introduced a dependency on the synapticon branch: the `object_code` member of the SDO info is not present in either `default` or `stable-1.5` of the IgH Mercurial repo.

**Comment by flosse** [comment]
Shall we add a `synapticon` feature that is disabled by default?

**Comment by birkenfeld** [comment]
Sounds good.
