### ISSUE TITLE
Licensing clarification: igh ethercat userspace library is LGPL

### ISSUE THREAD

**Issue by arwie** [ethercat-rs/ethercat#36]
From the documentation:
https://gitlab.com/etherlab.org/ethercat/-/jobs/artifacts/stable-1.5/raw/documentation/ethercat_doc.pdf?job=documentation

1.2 License
The master code is released under the terms and conditions of the GNU General Public
License (GPL [4]), version 2. Other developers, that want to use EtherCAT with Linux
systems, are invited to use the master code or even participate on development.
To allow static linking of userspace application against the master’s application inter-
face (see chapter 3), the userspace library (see section 7.2) is licensed under the terms
and conditions of the GNU Lesser General Public License (LGPL [5]), version 2.1.

**Comment by birkenfeld** [comment]
Thanks for the pointer, should be fixed now.
